sudo: required
language: minimal

git:
  depth: 2

services:
  - docker

env:
  global:
    - CONDAENV=python3.4
    - IMAGE_REPO=gcr.io/dd-decaf-cfbf6/gene-to-reactions
    - IMAGE_TAG=travis-ci-test
    - IMAGE=${IMAGE_REPO}:${IMAGE_TAG}

install:
  - echo ${DOCKER_PASSWORD} | docker login -u=decaftravis --password-stdin
  - docker build -t ${IMAGE} .
  - make setup

script:
  - make test-travis
  - make license

before_deploy:
  - ./scripts/install_gcloud.sh
  - ./scripts/install_kubectl.sh
  - docker tag ${IMAGE} ${IMAGE_REPO}:${TRAVIS_COMMIT::12}
  - docker tag ${IMAGE} ${IMAGE_REPO}:${TRAVIS_BRANCH}
  - docker push ${IMAGE_REPO}:${TRAVIS_COMMIT::12}
  - docker push ${IMAGE_REPO}:${TRAVIS_BRANCH}

deploy:
  provider: script
  script: ./scripts/deploy.sh
  on:
    all_branches: true

notifications:
  email: false
  slack:
    rooms:
      secure: "TrCGpyvBLkutZe9GaZJMihR/ZgJQN0yyZwkb7BItbveRDoAt4oBqZa7/DD0Rf78CEQreBeH5QiYL4PBEs9CcooJtJXDHBE8PaMYCicXgld3MS1AnMEpgE51zHIlZT/p5OPYA2RNBG/Vxla3IwTuWx5gcKmn3ofCHT/H+cUKKO2OqVLGXdM76YDSBSMHvDOyLwcjo7sq4i5k6EkfyTAOo5bdQycf2Uey5AYiki8TTcRdHQ+nXK8dYYIK/kWLsbKHU0OcuGJGUdYSscOe76b+v+6rWHb99lO+plkr/dkakfZoRN77g0TLGrHzOBX6DqSuLKpg+ziNfY7qFNsZQkRW60xn/eM1Vany7Fll5ovXf0MRVkJB5YIyBrUWLDK0lytRESPrqaCx+gF+HDw5Y59Gh5HAfyCAuRGhTTFxnXXSO+SYZauG/V0QTDMN3w+1awRZpCYSpyFdiCM0lxI1p/c3RdajpHuKE3G6nnW1kYBSmJYO/YJR71H3ZWK9UhpgSYrqibz6/8fAcxkQ3XWYN3dQo1x5fkNL9tmPCVtqJ6aDakBv7UjZN2GeA/TxyoxhVAendnvETk7s5DBsS8Yz6hfDdUpkN8pme3UFdC/m9ZP/Wn0/g5zwECRpY0JKpm/jybftgXJQJEr6pIWJXzwd62wwGA7QpG7TtFRJ4z2lDmsHk2Yc="
    on_success: never
    on_failure: always
    on_pull_requests: false
