sudo: required
language: python
env:
- CONDAENV=python3.4
services:
- docker
before_install:
- docker login -u=$DOCKER_USERNAME -p=$DOCKER_PASSWORD
install: docker-compose up -d
script:
- docker-compose exec web /bin/bash -c "nosetests"
after_success:
- docker-compose exec web /bin/bash -c "codecov --token $CODECOV_TOKEN"
deploy:
  provider: script
  script: ./push_to_hub.sh

