version: "3.2"
services:
  web:
    build: .
    image: eu.gcr.io/dd-decaf-cfbf6/gene-to-reactions:${IMAGE_TAG:-latest}
    networks:
      default:
      DD-DeCaF:
        aliases:
          - gene-to-reactions
    ports:
      - "${API_PORT:-8000}:8000"
    depends_on:
      - redis
    volumes:
      - ".:/app"
      - type: tmpfs
        target: "/prometheus-client"
    environment:
      - ENVIRONMENT=${ENVIRONMENT:-development}
      - SETTINGS_OBJECT=gene_to_reactions.settings.Default
      - ICE_HOST=${ICE_HOST:-ice.dd-decaf.eu}
      - ICE_PORT=${ICE_PORT:-443}
      - ICE_PASSWORD=${ICE_PASSWORD}
      - ICE_USER=${ICE_USER}
      - prometheus_multiproc_dir=/prometheus-client
    command: gunicorn -c gunicorn.py gene_to_reactions.app:app

  redis:
    image: redis
    ports:
      - 6379

networks:
  DD-DeCaF:
    external: true
