web:
  build: .
  dockerfile: Dockerfile
  links:
    - redis
  ports:
    - 6500:6500
  environment:
    - ICE_HOST
    - ICE_PASSWORD
    - ICE_PORT
    - ICE_USER
    - PYTHONUNBUFFERED=1
    - SETTINGS_OBJECT=gene_to_reactions.settings.Default
redis:
  image: redis
  ports:
    - 6379
