kind: Service
apiVersion: v1
metadata:
  name: gene-to-reactions-production
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8000"
spec:
  selector:
    app: gene-to-reactions
    env: production
  ports:
  - name: web
    protocol: TCP
    port: 80
    targetPort: 8000
